DEBUG 2021-06-01 12:03:35.009 UTC: 	 CRAB Client version: v3.210505
DEBUG 2021-06-01 12:03:35.010 UTC: 	 Running on: Linux cmslpc112.fnal.gov 3.10.0-1160.21.1.el7.x86_64 #1 SMP Tue Mar 16 08:00:44 CDT 2021 x86_64 x86_64 x86_64 GNU/Linux - Scientific Linux 7.9 (Nitrogen)
DEBUG 2021-06-01 12:03:35.010 UTC: 	 Executing command: 'status'
DEBUG 2021-06-01 12:03:35.010 UTC: 	 Found CRAB cache file /uscms/home/cannaert/.crab3
ERROR 2021-06-01 12:03:35.012 UTC: 	 Cannot find .requestcache file in CRAB project directory /uscms_data/d3/cannaert/UL2018_genproduction/Suu8TeV_chi1p5TeV/CMSSW_10_6_18/src/crab_projects/crab_MC_prod_Suu8TeV_chi1p5TeV_GENSIM_0001
ERROR 2021-06-01 12:03:35.012 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210505.00/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210505.00/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210505.00/lib/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210505.00/lib/CRABClient/Commands/SubCommand.py", line 270, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210505.00/lib/CRABClient/Commands/SubCommand.py", line 650, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210505.00/lib/CRABClient/Commands/SubCommand.py", line 512, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /uscms_data/d3/cannaert/UL2018_genproduction/Suu8TeV_chi1p5TeV/CMSSW_10_6_18/src/crab_projects/crab_MC_prod_Suu8TeV_chi1p5TeV_GENSIM_0001
INFO 2021-06-01 12:03:35.014 UTC: 	 Log file is /uscms_data/d3/cannaert/UL2018_genproduction/Suu8TeV_chi1p5TeV/CMSSW_10_6_18/src/crab.log
DEBUG 2021-06-01 12:03:51.318 UTC: 	 CRAB Client version: v3.210505
DEBUG 2021-06-01 12:03:51.319 UTC: 	 Running on: Linux cmslpc112.fnal.gov 3.10.0-1160.21.1.el7.x86_64 #1 SMP Tue Mar 16 08:00:44 CDT 2021 x86_64 x86_64 x86_64 GNU/Linux - Scientific Linux 7.9 (Nitrogen)
DEBUG 2021-06-01 12:03:51.319 UTC: 	 Executing command: 'status'
DEBUG 2021-06-01 12:03:51.319 UTC: 	 Found CRAB cache file /uscms/home/cannaert/.crab3
ERROR 2021-06-01 12:03:51.320 UTC: 	 Cannot find .requestcache file in CRAB project directory /uscms_data/d3/cannaert/UL2018_genproduction/Suu8TeV_chi1p5TeV/CMSSW_10_6_18/src/crab_projects/crab_MC_prod_Suu8TeV_chi1p5TeV_GENSIM_0001
ERROR 2021-06-01 12:03:51.320 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210505.00/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210505.00/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210505.00/lib/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210505.00/lib/CRABClient/Commands/SubCommand.py", line 270, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210505.00/lib/CRABClient/Commands/SubCommand.py", line 650, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210505.00/lib/CRABClient/Commands/SubCommand.py", line 512, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /uscms_data/d3/cannaert/UL2018_genproduction/Suu8TeV_chi1p5TeV/CMSSW_10_6_18/src/crab_projects/crab_MC_prod_Suu8TeV_chi1p5TeV_GENSIM_0001
INFO 2021-06-01 12:03:51.322 UTC: 	 Log file is /uscms_data/d3/cannaert/UL2018_genproduction/Suu8TeV_chi1p5TeV/CMSSW_10_6_18/src/crab.log
DEBUG 2021-06-01 12:04:48.959 UTC: 	 CRAB Client version: v3.210505
DEBUG 2021-06-01 12:04:48.959 UTC: 	 Running on: Linux cmslpc112.fnal.gov 3.10.0-1160.21.1.el7.x86_64 #1 SMP Tue Mar 16 08:00:44 CDT 2021 x86_64 x86_64 x86_64 GNU/Linux - Scientific Linux 7.9 (Nitrogen)
DEBUG 2021-06-01 12:04:48.959 UTC: 	 Executing command: 'submit'
DEBUG 2021-06-01 12:04:48.960 UTC: 	 Found CRAB cache file /uscms/home/cannaert/.crab3
INFO 2021-06-01 12:04:48.961 UTC: 	 Will use CRAB configuration file crab_diquark_GENSIM_prod_cfg.py
DEBUG 2021-06-01 12:04:48.961 UTC: 	 Loading CRAB configuration file.
DEBUG 2021-06-01 12:04:48.963 UTC: 	 Will use CRAB PrivateMC plugin (i.e. will run a MC generation job type).
ERROR 2021-06-01 12:04:48.964 UTC: 	 Working area '/uscms_data/d3/cannaert/UL2018_genproduction/Suu8TeV_chi1p5TeV/CMSSW_10_6_18/src/crab_projects/crab_MC_prod_Suu8TeV_chi1p5TeV_GENSIM_0001' already exists 
Please change the requestName in the config file
ERROR 2021-06-01 12:04:48.964 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210505.00/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210505.00/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210505.00/lib/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210505.00/lib/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210505.00/lib/CRABClient/ClientUtilities.py", line 399, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/uscms_data/d3/cannaert/UL2018_genproduction/Suu8TeV_chi1p5TeV/CMSSW_10_6_18/src/crab_projects/crab_MC_prod_Suu8TeV_chi1p5TeV_GENSIM_0001' already exists 
Please change the requestName in the config file
INFO 2021-06-01 12:04:48.965 UTC: 	 Log file is /uscms_data/d3/cannaert/UL2018_genproduction/Suu8TeV_chi1p5TeV/CMSSW_10_6_18/src/crab.log
