DEBUG 2021-09-08 15:27:58.695 UTC: 	 CRAB Client version: v3.210825
DEBUG 2021-09-08 15:27:58.695 UTC: 	 Running on: Linux cmslpc154.fnal.gov 3.10.0-1160.36.2.el7.x86_64 #1 SMP Mon Jul 26 08:21:44 CDT 2021 x86_64 x86_64 x86_64 GNU/Linux - Scientific Linux 7.9 (Nitrogen)
DEBUG 2021-09-08 15:27:58.695 UTC: 	 Executing command: 'submit'
DEBUG 2021-09-08 15:27:58.696 UTC: 	 Found CRAB cache file /uscms/home/cannaert/.crab3
INFO 2021-09-08 15:27:58.697 UTC: 	 Will use CRAB configuration file crab_diquark_HLT_prod_new.cfg
DEBUG 2021-09-08 15:27:58.697 UTC: 	 Loading CRAB configuration file.
ERROR 2021-09-08 15:27:58.703 UTC: 	 Unhandled Exception!
ERROR 2021-09-08 15:27:58.703 UTC: 	 No module named crab_diquark_HLT_prod_new.cfg
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/SubCommand.py", line 56, in loadConfig
    self.configuration = loadConfigurationFile(os.path.abspath(configname))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/WMCore/Configuration.py", line 589, in loadConfigurationFile
    modPath = imp.find_module(cfgBaseName, [cfgDirName])
ImportError: No module named crab_diquark_HLT_prod_new.cfg
ERROR 2021-09-08 15:27:58.705 UTC: 	 ERROR: ImportError: No module named crab_diquark_HLT_prod_new.cfg
ERROR 2021-09-08 15:27:58.705 UTC: 	 
	Please email hn-cms-computing-tools@cern.ch for support with the crab.log file or crab.log URL.
ERROR 2021-09-08 15:27:58.705 UTC: 	 	Client Version: v3.210825
ERROR 2021-09-08 15:27:58.705 UTC: 	 	Please use 'crab uploadlog' to upload the log file /uscms_data/d3/cannaert/UL2018_genproduction/totalProcess/Suu4TeV_chi500GeV/CMSSW_10_2_16_UL/src/crab.log to the CRAB cache.
DEBUG 2021-09-08 15:28:18.594 UTC: 	 CRAB Client version: v3.210825
DEBUG 2021-09-08 15:28:18.595 UTC: 	 Running on: Linux cmslpc154.fnal.gov 3.10.0-1160.36.2.el7.x86_64 #1 SMP Mon Jul 26 08:21:44 CDT 2021 x86_64 x86_64 x86_64 GNU/Linux - Scientific Linux 7.9 (Nitrogen)
DEBUG 2021-09-08 15:28:18.595 UTC: 	 Executing command: 'submit'
DEBUG 2021-09-08 15:28:18.595 UTC: 	 Found CRAB cache file /uscms/home/cannaert/.crab3
INFO 2021-09-08 15:28:18.596 UTC: 	 Will use CRAB configuration file crab_diquark_HLT_prod_new.cfg
DEBUG 2021-09-08 15:28:18.596 UTC: 	 Loading CRAB configuration file.
ERROR 2021-09-08 15:28:18.597 UTC: 	 Unhandled Exception!
ERROR 2021-09-08 15:28:18.597 UTC: 	 No module named crab_diquark_HLT_prod_new.cfg
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/SubCommand.py", line 56, in loadConfig
    self.configuration = loadConfigurationFile(os.path.abspath(configname))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/WMCore/Configuration.py", line 589, in loadConfigurationFile
    modPath = imp.find_module(cfgBaseName, [cfgDirName])
ImportError: No module named crab_diquark_HLT_prod_new.cfg
ERROR 2021-09-08 15:28:18.599 UTC: 	 ERROR: ImportError: No module named crab_diquark_HLT_prod_new.cfg
ERROR 2021-09-08 15:28:18.599 UTC: 	 
	Please email hn-cms-computing-tools@cern.ch for support with the crab.log file or crab.log URL.
ERROR 2021-09-08 15:28:18.599 UTC: 	 	Client Version: v3.210825
ERROR 2021-09-08 15:28:18.599 UTC: 	 	Please use 'crab uploadlog' to upload the log file /uscms_data/d3/cannaert/UL2018_genproduction/totalProcess/Suu4TeV_chi500GeV/CMSSW_10_2_16_UL/src/crab.log to the CRAB cache.
DEBUG 2021-09-08 15:28:21.938 UTC: 	 CRAB Client version: v3.210825
DEBUG 2021-09-08 15:28:21.939 UTC: 	 Running on: Linux cmslpc154.fnal.gov 3.10.0-1160.36.2.el7.x86_64 #1 SMP Mon Jul 26 08:21:44 CDT 2021 x86_64 x86_64 x86_64 GNU/Linux - Scientific Linux 7.9 (Nitrogen)
DEBUG 2021-09-08 15:28:21.939 UTC: 	 Executing command: 'submit'
DEBUG 2021-09-08 15:28:21.939 UTC: 	 Found CRAB cache file /uscms/home/cannaert/.crab3
INFO 2021-09-08 15:28:21.940 UTC: 	 Will use CRAB configuration file crab_diquark_HLT_prod_new.cfg
DEBUG 2021-09-08 15:28:21.940 UTC: 	 Loading CRAB configuration file.
ERROR 2021-09-08 15:28:21.941 UTC: 	 Unhandled Exception!
ERROR 2021-09-08 15:28:21.941 UTC: 	 No module named crab_diquark_HLT_prod_new.cfg
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/bin/crab", line 151, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/bin/crab", line 136, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/CRABClient/Commands/SubCommand.py", line 56, in loadConfig
    self.configuration = loadConfigurationFile(os.path.abspath(configname))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.210825.00/lib/WMCore/Configuration.py", line 589, in loadConfigurationFile
    modPath = imp.find_module(cfgBaseName, [cfgDirName])
ImportError: No module named crab_diquark_HLT_prod_new.cfg
ERROR 2021-09-08 15:28:21.943 UTC: 	 ERROR: ImportError: No module named crab_diquark_HLT_prod_new.cfg
ERROR 2021-09-08 15:28:21.943 UTC: 	 
	Please email hn-cms-computing-tools@cern.ch for support with the crab.log file or crab.log URL.
ERROR 2021-09-08 15:28:21.943 UTC: 	 	Client Version: v3.210825
ERROR 2021-09-08 15:28:21.943 UTC: 	 	Please use 'crab uploadlog' to upload the log file /uscms_data/d3/cannaert/UL2018_genproduction/totalProcess/Suu4TeV_chi500GeV/CMSSW_10_2_16_UL/src/crab.log to the CRAB cache.
